name: engine

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: open-ledger
      POSTGRES_PASSWORD: open-ledger
      POSTGRES_DB: engine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build: .
    env_file:
      - .env
    command: yarn test:cov
    volumes:
      - .:/engine
    depends_on:
      - database
    links:
      - database

  migrate:
    build: .
    env_file:
      - .env
    command: yarn migrate
    volumes:
      - .:/engine
    depends_on:
      database:
        condition: service_healthy
    links:
      - database

  app:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    command: yarn start:debug
    volumes:
      - .:/engine
    depends_on:
      database:
        condition: service_healthy
    links:
      - database