export enum ErrorCode {
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
	INVALID_PARAMETERS = 'INVALID_PARAMETERS',
	INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',

	INVALID_AMOUNT = 'INVALID_AMOUNT',

	ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
	ASSET_NOT_FOUND = 'ASSET_NOT_FOUND',

	TRANSACTION_AMBIGUOUS_ACCOUNT = 'TRANSACTION_AMBIGUOUS_ACCOUNT',
	TRANSACTION_MUST_HAVE_AT_LEAST_ONE_DEBIT_AND_CREDIT_OPERATION = 'TRANSACTION_MUST_HAVE_AT_LEAST_ONE_DEBIT_AND_CREDIT_OPERATION',
	TRANSACTION_OPERATIONS_TOTAL_AMOUNT_BALANCE = 'TRANSACTION_OPERATIONS_TOTAL_AMOUNT_BALANCE',
	TRANSACTION_OPERATIONS_TOTAL_AMOUNT_MISMATCH = 'TRANSACTION_OPERATIONS_TOTAL_AMOUNT_MISMATCH',
}
