export enum ErrorCode {
	INVALID_PARAMETERS = 'INVALID_PARAMETERS',
	INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
	INSUFFICIENT_WALLET_TYPE_PERMISSIONS = 'INSUFFICIENT_WALLET_TYPE_PERMISSIONS',
	PROVIDER_NOT_FOUND = 'PROVIDER_NOT_FOUND',
	WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
	UNAUTHORIZED_TRANSFER = 'UNAUTHORIZED_TRANSFER',
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
	TRANSFER_AMOUNT_MUST_BE_GREATER_THAN_ZERO = 'TRANSFER_AMOUNT_MUST_BE_GREATER_THAN_ZERO',
	TRANSFER_AUTHORIZER_PROVIDER_ERROR = 'TRANSFER_AUTHORIZER_PROVIDER_ERROR',
}
