export enum ViolationCode {
	INVALID_UUID = 'INVALID_UUID',
	INVALID_DECIMAL = 'INVALID_DECIMAL',
	INVALID_FORMAT = 'INVALID_FORMAT',
	BAD_LENGTH = 'BAD_LENGTH',
	MIN_LENGTH = 'MIN_LENGTH',
	PASSWORD_AT_LEAST_ONE_DIGIT = 'PASSWORD_AT_LEAST_ONE_DIGIT',
	PASSWORD_AT_LEAST_ONE_SPECIAL_CHARACTER = 'PASSWORD_AT_LEAST_ONE_SPECIAL_CHARACTER',
}
